mkdir plots
python p110_scaling_features.py > ./plots/batch.txt
python p115_l1_l2_regularization.py  >> ./plots/batch.txt
python p119_squential_backward_selection.py  >> ./plots/batch.txt
python p124_random_forest.py  >> ./plots/batch.txt
python p124_random_forest_feature_importance.py  >> ./plots/batch.txt
python p131_principal_component_analysis.py  >> ./plots/batch.txt
python p141_linear_descriminant_analsys.py  >> ./plots/batch.txt
python p154_pca_nonlinear_mapings.py  >> ./plots/batch.txt
python p177_k_fold_cross_validation.py  >> ./plots/batch.txt
python p181_learning_curves.py  >> ./plots/batch.txt
python p186_grid_search.py  >> ./plots/batch.txt
python p189_nested_cross_validation.py  >> ./plots/batch.txt
python p190_confusion_matrix.py  >> ./plots/batch.txt
python p193_model_precision_recall.py  >> ./plots/batch.txt
python p194_receiver_operating_characteristic.py  >> ./plots/batch.txt
python p206_majority_vote_classifier.py  >> ./plots/batch.txt
python p221_bagging_bootstrap_samples.py  >> ./plots/batch.txt
python p229_adaboost.py  >> ./plots/batch.txt
python p25_perceptron.py  >> ./plots/batch.txt
python p314_k_means.py  >> ./plots/batch.txt
python p322_silhouette_plots.py  >> ./plots/batch.txt
python p330_dendogram.py  >> ./plots/batch.txt
python p356_neural_net.py  >> ./plots/batch.txt
python p36_adaline_gd.py  >> ./plots/batch.txt
python p411_keras.py  >> ./plots/batch.txt
python p44_adaline_sgd.py  >> ./plots/batch.txt
python p51_standard_scalar.py  >> ./plots/batch.txt
python p62_logistic_regression.py  >> ./plots/batch.txt
python p73_support_vector_machine.py  >> ./plots/batch.txt
python p75_xor_dataset.py  >> ./plots/batch.txt
python p78_support_vector_machine_gamma.py  >> ./plots/batch.txt
python p86_decision_tree.py  >> ./plots/batch.txt
python p94_knearest_neighbors.py  >> ./plots/batch.txt
python q0_simple_e13b_display.py  >> ./plots/batch.txt
python q1_database_statistics.py  >> ./plots/batch.txt
python q2_tensorflow_mnist.py  >> ./plots/batch.txt
python q2_Theano_mlp.py  >> ./plots/batch.txt
python q3_removing_affine_distortion.py

